name: 'hello world container action'
inputs:
  myInput:
    required: true
    default: 'Awesome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'